### ISSUE TITLE
AtemFrame.FromRGBA results in incorrect alpha channel

### ISSUE THREAD

**Issue by senseisimonp** [LibAtem/LibAtem#10]
Resulting alpha channel is partially derived from luminance

**Comment by senseisimonp** [comment]
It's just a typo in BT709ColourSpaceConverter line 60 

res[i + 3] = res[i] = (byte) (y1 & 0xff);

should be 

res[i + 3] = (byte) (y1 & 0xff);

**Comment by Julusian** [comment]
Good spot, I have pushed a fix
