### ISSUE TITLE
Can't control Mic for Atem Mini Pro (8.5)

### ISSUE THREAD

**Issue by Meldur** [LibAtem/LibAtem#12]
Hello,

I'm not able to control the microphones on an ATEM Mini Pro with firmware 8.5. The FairlightMixerSourceSetCommand is ignored without any response.

Any idea?

PS: Great project!! :)

**Comment by Julusian** [comment]
What are you trying to change? Have you double checked the sourceId you are passing too?
I can confirm this does work for FaderGain and Gain on my mini when the channel is in split-mono mode

```
var client = new AtemClient("10.42.13.95");
client.Connect();
client.OnConnection += (sender) =>
{
    client.SendCommand(new FairlightMixerSourceSetCommand()
    {
        Mask = FairlightMixerSourceSetCommand.MaskFlags.Gain,
        Index = AudioSource.Mic1,
        SourceId = -256,
        Gain = -10
    });
    Console.WriteLine("Sent");
};

while(true){}
```

**Comment by Meldur** [comment]
Thanks for your reply. I figured out similar. The problem was, that the SourceID is 0 by default - can you please tell where the -256 from?

**Comment by Julusian** [comment]
That is what the atem tells us it is. If you listen for `FairlightMixerSourceGetCommand` from the atem, or use LibAtem.State to build a state tree, then you can see the source ids you should use.

I have not seen enough of a pattern to identify/translate those. The sourceId will vary depending on the mode of the input (stereo/mono/dual-mono)

**Comment by Meldur** [comment]
Aaaahh. I understand. Thanks!!!!
