### ISSUE TITLE
Provide NuGet Package for this library

### ISSUE THREAD

**Issue by sensslen** [LibAtem/LibAtem#14]
Are there any plans to provide a NuGet package for this library?

**Comment by Julusian** [comment]
I probably should, but am lacking motivation to figure out how to publish c# on nuget.
For ages this library wasn't complete enough to publish, and since then I have mostly been using it as a testing ground for reverse engineering work

**Comment by sensslen** [comment]
OK, I see. Thanks for the feedback.
