### ISSUE TITLE
Command length value

### ISSUE THREAD

**Issue by H0fek** [LibAtem/LibAtem#5]
Hi,
I tested your lib with ATEM Television Studio and I have a question. I get **SerializationException** in **Deserialize** method in **AutoSerializeBase** class when connecting (before SendCommand).

```csharp
static void Main(string[] args)
{
     using (AtemClient atemClient = new AtemClient("192.168.1.241", true))
     {
         atemClient.SendCommand(new ProgramInputSetCommand { Index = 0, Source = LibAtem.Common.VideoSource.Input1 });
    }            
}      
```

It seems that this ATEM uses different command lengths in **AudioMixerInputGetCommand** and **TopologyCommand**. If I change them according to _cmd.BodyLength_, then there are no problems, but I'm not sure if I did this the right way. 

Does concept with "Device template" which would edit those lengths make sense? For example: 
- ATEM Television template: set length to 24
- ATEM Television HD template: set length to 20

Or maybe there is already solution to this?

My firmware/driver version: 8.0.1

**Comment by Julusian** [comment]
Interestingly, I am not getting this issue with my TVS running 8.0.1

Can you check what git revision of this library you are using? 
It sounds like the library is either too old to work with 8.0.1+ firmware (but anything within the last few months should be new enough), or the library failed to determine the firmware version running on the atem.
There are multiple versions of a few of the commands, as different firmware versions do things differently. For the 8.0.1 firmware, it should have auto selected the TopologyV8Command and AudioMixerInputGetV8Command which will already have the correct lengths defined.

There isnt a need for "device templates", as there are very few or no commands that have a varying length based on model. It mostly varies based on firmware version, or some are always dynamic length and so are handled differently.

**Comment by Julusian** [comment]
If you are running a recent version, could you run this and send the resulting `test.data` file it generates. This will let me see exactly what your atem sent so will hopefully help with reproducing the issue.

```csharp
        static void Main(string[] args)
        {
            using (AtemClient atemClient = new AtemClient("10.42.13.96", false))
            {
                var str = new List<string>();
                atemClient.OnReceivePacket += (sender, pkt) =>
                {
                    str.Add(BitConverter.ToString(pkt.Payload));
                };
                atemClient.OnReceive += (sender, cmds) =>
                {
                    if (cmds.Any(c => c is InitializationCompleteCommand))
                    {
                        File.WriteAllLines("test.data", str);
                        Console.WriteLine("done");
                    }
                };

                atemClient.Connect();
                atemClient.SendCommand(new ProgramInputSetCommand { Index = 0, Source = LibAtem.Common.VideoSource.Input1 });
            }
        }
```

**Comment by H0fek** [comment]
Well, issue can be closed. Magically everything is working now over night. 

I use master branch, today I pulled some changes, so it's the newest. I think that might be caused because of my BM drivers testing and constant firmware flashing. Maybe in some point I forgot to restart my computer/TVS. Last thing I was doing with my computer yesterday were some restarts, because I was testing my GPU. Maybe that triggered something as I was using 7.5.2 earlier. 

I attach requested file as It might tell you something, but I doubt it :D Thanks and sorry for bothering.
[test.zip](https://github.com/LibAtem/LibAtem/files/5005691/test.zip)

**Comment by Julusian** [comment]
interesting.. pc restarts wont have any effect as this library doesnt use anything the blackmagic software installs, but not restarting the atem could be a cause. But as its working now I wont look into it any further.
I'm glad its working for you now :)
