### ISSUE TITLE
Current Master not compiling due to small errors

### ISSUE THREAD

**Issue by imorrish** [LibAtem/LibAtem#6]
LibAtem\Common\Recording.cs has an enum "Removed"causing an issue
LibAtem.State\Builder\StreamingStateUpdater.cs has "else if (command is StreamingTimecodeCommand timecodeCmd)" causing an issue.

I forgot to record the issues, just removed them from code and everything was good. Could easily be something I'm doing wrong.

**Comment by Julusian** [comment]
Sorry, I missed this one. It is fixed now
