### ISSUE TITLE
Is there some way to have the Get commands reflect the current hardware status

### ISSUE THREAD

**Issue by imorrish** [LibAtem/LibAtem#7]
My C# skills are very basic, trying to figure out the best way to have a class that holds the current value of say ME Program input.  Would that have to be updated from Client.OnReceive?

Thinking to have a contructor for new client that creates class instances for objects like ME's so that standard gettter would reflect current hardware values (unless you code already does this but I'm missing something)

**Comment by Julusian** [comment]
I think that LibAtem.State is what you are looking for there. It looks like I havent made the usage very pretty yet, but an example of how to hook it up is https://github.com/LibAtem/AtemUI/blob/master/AtemServer/AtemRepository.cs#L73

This gives a large blob of classes (which gets updated in place), which is designed to be serializable to json or other formats. There are no setters on those classes for now,

**Comment by imorrish** [comment]
Awesome, that should work. Thanks for all the work you have done on this. Just found out how easy it is to create the macro codes. Posted this on ATEM forum to answer a developers question https://forum.blackmagicdesign.com/viewtopic.php?f=12&t=120898.

I'll be adding more functionality to the PowerShell module shortly. Been using it on a Raspberry Pi.
